### PR TITLE
[ALOY-1316] Support use of $.args.* in any XML attribute or TSS property

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/ALOY-1316

Not sure if it's a good idea to treat `'$.args.*'` as an expression. Maybe we should differentiate a `string` and a js `expression` when setting properties.

### CODE REVIEW

**Comment by brentonhouse** [comment]
@feons - Checking to see what needs to updated to merge.

**Comment by feons** [comment]
@brentonhouse, rebased. Please shower this with some review love!

**Comment by brentonhouse** [comment]
@ewanharris - Is this PR something we can merge now?

**Comment by ewanharris** [comment]
@feons, @brentonhouse. I'd noticed an [open ticket](https://jira.appcelerator.org/browse/ALOY-1610)from @Topener about allowing controller created variables to be used in tss, his third suggestion is related to using `$` to allow this. What do you think about expanding this PR to allow this usage?

```
// mapview.js
$.timap = require('ti.map');
 
// mapview.tss
type: $.timap.POLYLINE_PATTERN_DASHED,
```

**Comment by brentonhouse** [comment]
@ewanharris - sounds good!

**Pull request merged**
