### PR TITLE
[ALOY-1358] Support Ti.UI.iOS.BlurView in XML

### PR DESCRIPTION
**Pull request by FokkeZB**
https://jira.appcelerator.org/browse/ALOY-1358

### CODE REVIEW

**Comment by feons** [comment]
@FokkeZB, could you also include a test app?

**Comment by FokkeZB** [comment]
O man, serious.. it's a no-brianer :dancers: 

(but I will if it makes you - or @ingo - happy)

**Comment by feons** [comment]
QEs will appreciate it too!

**Comment by FokkeZB** [comment]
@feons test app added:
https://github.com/appcelerator/alloy/commit/482bce740f957833af9adddc9161dac127bb50c2#diff-51732461d5443d23f1642cc012dd1dfbR34

**Comment by feons** [comment]
**Approved.**

**Pull request merged**
