### PR TITLE
fix README links

### PR DESCRIPTION
**Pull request by dfrankow**
Maybe these README links are correct?

### CODE REVIEW

**Comment by dfrankow** [comment]
When I try to sign the CLA I get:

```
Something went wrong...
[echosign] Unexpected status code
```

**Comment by feons** [comment]
@dfrankow, could you try to sign the CLA again?  It's working for me.

**Comment by dfrankow** [comment]
Same problem:

```Something went wrong...
[echosign] Unexpected status code```

**Comment by feons** [comment]
@dfrankow, refers to https://jira.appcelerator.org/browse/CLA-12, you should be able to sign the CLA now!

**Comment by dfrankow** [comment]
Worked!

I can't see the jira, likely because I didn't make an account, but that's okay.

**Comment by jawa9000** [comment]
Is there a Jira ticket related to this PR?

**Comment by hansemannn** [comment]
@jawa9000 No, it was only a typo fix.

**Pull request merged**
