### PR TITLE
regex change to support {{ }}

### PR DESCRIPTION
**Pull request by dbankier**
Alloy is currently catching and interpreting `{{ }}` as an alloy binding when it should only catch `{ }`.
This change is needed for https://github.com/dbankier/nano.

### CODE REVIEW

**Comment by FokkeZB** [comment]
The Travis CI build seems to have [failed](https://travis-ci.org/appcelerator/alloy/builds/46043907) over nothing, but @sfeather might be right that it also needs changes where the regexp is used because the full match now includes the character before and after. The compiler only [uses the regexp](https://github.com/dbankier/alloy/blob/double-brace/Alloy/commands/compile/styler.js#L520) on style values, so it might indeed work the way it is but it *does* do some replacements after line 520 that will now include the character before or after (if any, e.g. in values with multiple `{name}` in one value?)

**Comment by dbankier** [comment]
went back to tony's original and used a negative lookahead instead.
So yes it will still catch `{{ name}` but `{{ name }}` is safe.

**Comment by FokkeZB** [comment]
Good one ;)

**Comment by skypanther** [comment]
Thanks @FokkeZB and @dbankier

The travis failure is unrelated. I thought it was simply a timeout issue, but it keeps popping up. I'll resolve that in [ALOY-1222](https://jira.appcelerator.org/browse/ALOY-1222)

**Comment by skypanther** [comment]
I'd appreciate it if you'd add a test case to the PR. You could create a copy of the binding_no_persistence app and maybe add an extra label with non-binding {{foo}} text.

Having done that, I see that this PR works but not in all cases. For example, using the modified binding_no_persistence app:

```xml
<!-- adding before the table, this works as expected -->
<Label top="20" text="{{This is not a binding reference}}"/>

<!-- Then, trying some variations in the data-bound tableview -->
<TableViewRow title="{name}"/> <!-- works -->
<TableViewRow title="My hero is {name}"/> <!-- fails -->
<TableViewRow title="{name} and {{name}}"/>  <!-- fails -->
```

Log output includes:

```
[DEBUG] {title:typeof __alloyId2.__transform['name'] !== 'undefined' ? __alloyId2.__transform['name'] :
 My hero is '+__alloyId2.get('name') +',}
```

Looks like strings aren't being properly quoted.

Make sure to also create new _generated code before running the jake tests with:

```shell
node tools/create_generated_code.js testing/ALOY-1219
```

**Comment by skypanther** [comment]
I meant to include a link to https://jira.appcelerator.org/browse/ALOY-443 where mixed binding string support was added.

**Comment by dbankier** [comment]
@skypanther. Done and passing without a change.

These two are not valid test cases for this issue and a separate issue should be raised and the issue existed before:

~~~
<TableViewRow title="My hero is {name}"/> <!-- fails -->
<TableViewRow title="{name} and {{name}}"/>  <!-- fails -->
~~~

Simple reason is that alloy databinding never supported this:

~~~
<TableViewRow title="My hero is {name}"/> <!-- fails -->
~~~

**Comment by jhaynie** [comment]
sweet. this will be cool

**Comment by dbankier** [comment]
@jhaynie fast-track? :)

**Comment by dbankier** [comment]
Just to update my comment before with a conversation with @skypanther:
screen shot 2015-01-08 at 9 20 52 am

**Comment by dbankier** [comment]
Ok, I modified and squashed all the test commits. Done.

**Comment by skypanther** [comment]
**APPROVED** and merged. Thanks @dbankier

**Comment by dbankier** [comment]
Excellent! Thanks.

**Pull request merged**
