### PR TITLE
Allow for Alloy.Globals and Alloy.CFG in views

### PR DESCRIPTION
**Pull request by rborn**
Fixes: https://jira.appcelerator.org/browse/ALOY-1021

### CODE REVIEW

**Comment by feons** [comment]
@rborn, thank you for the PR!
I'd appreciate it if you'd add a test case.

**Comment by rborn** [comment]
In my case I need to use FontAwsome to show some labels in a listview directly in xml.
~~~
<ListItem itemId="tabHelp" tabTitle:text="L('drawer_help')" tabImage:text="Alloy.Globals.FA.faQuestion"/>
~~~

Where `Alloy.Globals.FA` is an object containing FontAwsome symbols.

However there are many cases where you would want to use `Alloy.Globals` or `Alloy.CFG` in the views directly.

**Comment by feons** [comment]
@rborn, thank you!

**Comment by feons** [comment]
Looks good! **APPROVED.**

**Pull request merged**
