### PR TITLE
 [ALOY-1524] Replace wrench with fs-extra

### PR DESCRIPTION
**Pull request by m1ga**
JIRA-Ticket: https://jira.appcelerator.org/browse/ALOY-1524

### CODE REVIEW

**Comment by m1ga** [comment]
Nice. Node 5.9 test is complete, only the node 4.4 test is ending with "The job exceeded the maximum time limit for jobs, and has been terminated."

**Comment by sgtcoolguy** [comment]
@feons I'd really like to see us keep up to date with 3rd-party dependencies here. While `wrench` has served us well in the past, the author is pretty explicitly asking people to move on to `fs-extra` now (it even spits out a message during `npm install`). Any chance we can review and get this in?

**Comment by feons** [comment]
@m1ga, @sgtcoolguy, is this still WIP?

**Comment by feons** [comment]
@m1ga, thanks! Tests passed locally. Merging...

**Pull request merged**
