### PR TITLE
[ALOY-1537] Update uglify-js and moment.js

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/ALOY-1537

### CODE REVIEW

**Comment by wluu** [comment]
@ingo 

I ran the retire.js on this PR and get the following vulnerabilities:
```
/Users/wluu/github/appc-cli/node_modules/alloy/test/apps/testing/underscore/assets/vendor/jquery.js
  ↳ jquery 1.7.2 has known vulnerabilities: severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/ severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
/Users/wluu/github/appc-cli/node_modules/alloy/test/apps/testing/backbone/assets/vendor/jquery-1.7.1.js
 ↳ jquery 1.7.1 has known vulnerabilities: severity: medium; bug: 11290, summary: Selector interpreted as HTML; http://bugs.jquery.com/ticket/11290 http://research.insecurelabs.org/jquery/test/ severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
```

The vulnerabilities are appearing in the `test` directory, so I'm not sure if we want to whitelist them. **However,** there are couple of things to note: 

- jquery seems to be indirectly used [here](https://github.com/appcelerator/alloy/blob/master/Alloy/lib/alloy/backbone/1.1.2/backbone.js#L174-L176) and [here](https://github.com/appcelerator/alloy/blob/master/Alloy/lib/alloy/underscore.js#L1331-L1337)
- When I was using backbone and underscore test suite, security vulnerabilities still appeared with jquery 1.12.4 and 2.2.4. Security vulnerabilities did not appear in jquery 3.1.1.
- But, when I ran the test suite with jquery 3.1.1, lots of test cases were failing.

**Comment by ingo** [comment]
alloy should .npmignore those directories with test files. It appears it already is:

https://github.com/appcelerator/alloy/blob/master/.npmignore

Maybe a new version needs to be published?

**Comment by wluu** [comment]
@ingo 

Yeah, it looks like the `update_dev` branch doesn't have those entries: https://github.com/feons/alloy/blob/update_dev/.gitignore

**Comment by wluu** [comment]
@ingo, Instead, should I create a  `.retireignore` file since the last alloy build didn't ignore those test suites: https://jenkins.appcelerator.org/job/alloy/474/console

**Comment by ingo** [comment]
@wluu you should do both. .retireignore will prevent retire from scanning them (and thus alloy developers won't see them). .npmignore will prevent them from being published (and thus alloy consumers won't get them)

**Comment by wluu** [comment]
@ingo, Added `.retireignore` to the PR. The `.npmignore` was already there.

**Comment by ingo** [comment]
LGTM _except_ there are 742 files in this PR. A lot of them look like formatting changes. Are those required?

**Comment by wluu** [comment]
Looks like a lot of these changes are for unit tests and sample apps. And, they seem valid because of this weird syntax: https://github.com/appcelerator/alloy/pull/812/files?diff=split#diff-6f1c905a028c763bee10d516bd65bc13L15

**Comment by ingo** [comment]
Okay, otherwise I'm fine if you merge.

**Pull request merged**
