### PR TITLE
DO NOT MERGE [ALOY-1596] Mobileweb assets copied on alloy new

### PR DESCRIPTION
**Pull request by ewanharris**
https://jira.appcelerator.org/browse/ALOY-1596

Where we had mobileweb as a platform in tests I figured that it would make sense to replace with windows, everything passes for me locally on osx

### CODE REVIEW

**Comment by ewanharris** [comment]
Included 7d771dd2b4df8a4fab8e61f8fb51d62322b65a37 in this pr, walk-sync returns paths with posix separators so we don't need to bother with win32 seperators. All test pass for me on windows (albeit very slowly!)

```
Finished in 2834.968 seconds
3357 specs, 0 failures
```

**Comment by feons** [comment]
*LGTM.*

**Comment by feons** [comment]
@ewanharris, totally missed the DO NOT MERGE headline! I'm not able to reopen this, you probably need to push the changes again, sorry about it!

**Comment by ewanharris** [comment]
@feons np! 😄  When are we aiming for including this? Based off what I know, I'm not sure how we can keep `platform=mobileweb` and `OS_MOBILEWEB` working while removing the assets from the template?

**Comment by feons** [comment]
@ewanharris, to not break existing apps, I think we need to keep the file `platforms/mobileweb/index.js`.

**Pull request merged**
