### PR TITLE
[ALOY-1356] Add support for LivePhotoView under Ti.UI.iOS namespace

### PR DESCRIPTION
**Pull request by FokkeZB**
https://jira.appcelerator.org/browse/ALOY-1356

### CODE REVIEW

**Comment by feons** [comment]
@FokkeZB, test app please! :) Thank you!

**Comment by FokkeZB** [comment]
Deal, if you do https://jira.appcelerator.org/browse/ALOY-1357 for 5.2.0 :)

**Comment by FokkeZB** [comment]
Added test app:
https://github.com/appcelerator/alloy/commit/191b09ac08a29396311c63f6470596030568d75a#diff-3e419e88533b938e7a7c8e95f6edc935R34

**Comment by feons** [comment]
**Approved.**

**Pull request merged**
