### PR TITLE
[ALOY-961] added support for AttributedString

### PR DESCRIPTION
**Pull request by k0sukey**
JIRA https://jira.appcelerator.org/browse/ALOY-961

### CODE REVIEW

**Comment by k0sukey** [comment]
@Mattijah Ohhh, Android support. Okay. Remove the namespace of iOS.

@skypanther I think this PR is the need for attributedHintText in Ti.UI.TextField. And controller also to be clean than the example code of ticket. How about?

**Comment by skypanther** [comment]
Thanks @k0sukey this looks good. But I'm going to have to wait for TIMOB-18062 to be resolved to properly test it. The SDK team has yet to add support for Ti.UI.AttributedString to 3.6.0 master. 

Could you add the following to test\specs\compile.js?

First, add `exec = require('child_process').exec` to the variable definitions at the top of the file. Then, after the var EXCLUDE_FOLDERS statement, add:

```javascript
// Skip ALOY-961 / AttributedString when using pre-3.6.0 SDKs
exec('ti sdk list --output json', function (error, stdout, stderr) {
	if (error === null) {
		var sdkInfo = JSON.parse(stdout);
		if(sdkInfo.activeSDK < '3.6.0') {
			EXCLUDE_FOLDERS.push(TEST_FOLDER+sep+'ALOY-961');
		}
	}
});
```

**Comment by k0sukey** [comment]
@skypanther Thanks, added EXCLUDE_FOLDERS. Use the ```Alloy/tiapp``` in SDK version compare.

**Comment by skypanther** [comment]
The blocking ticket has been resolved. All tests pass locally. Travis tests fail because of incomplete TiSDK setup in our travis.yml configuration. I'll fix up that issue.

**APPROVED**

**Pull request merged**
