### PR TITLE
[TIMOB-24817] Support Widgets in ListView templates

### PR DESCRIPTION
**Pull request by garymathews**
##### REQUIRES https://github.com/appcelerator/titanium_mobile/pull/9955

- Support defining Alloy widgets in ListView templates

###### TEST CASE
```XML
<Alloy>
	<Window class="container" backgroundColor="white">
		
        <ListView id="listView" defaultItemTemplate="template">
            <Templates>
                <ItemTemplate name="template">
                    <Widget src="test.widget" bindId="testWidget" id="testWidget"/>
                </ItemTemplate>
            </Templates>

            <ListSection headerTitle="WIDGETS">
                <ListItem testWidget:backgroundColor="red" />
                <ListItem testWidget:backgroundColor="blue" />
                <ListItem testWidget:backgroundColor="orange" />
            </ListSection>
        </ListView>

	</Window>
</Alloy>
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24817)

### CODE REVIEW

**Comment by feons** [comment]
@garymathews, what's the structure of `test.widget`?

**Comment by garymathews** [comment]
@feons Here's my simple test widget: https://jira.appcelerator.org/secure/attachment/65018/test.widget.zip

**Comment by feons** [comment]
@garymathews, what's the expected output here? I see the text `TEST1` against a white background.

**Comment by guiled** [comment]
Will it be possible to bind a widget (using bindId property) ?

**Comment by garymathews** [comment]
@feons updated both PRs 👍

**Comment by feons** [comment]
@garymathews, looks good. Please update the package version!

**Comment by feons** [comment]
**Approved.**

**Comment by hansemannn** [comment]
Was this tested before? Just tried with SDK 7.4.0 and Alloy 1.13.0 and it throws a build error:
```xml
<Alloy>
		<Window>
			<ListView id="listView" defaultItemTemplate="Cell">
				<Templates>
					<ItemTemplate name="Cell">
						<View height="250">
						        <Widget src="my.widget" bindId="testWidget" id="testWidget"/>
						</View>
					</ItemTemplate>
				</Templates>
				<ListSection>
					<ListItem></ListItem>
				</ListSection>
			</ListView>
		</Window>
</Alloy>
```
Error:
```
[DEBUG] /usr/local/lib/node_modules/alloy/Alloy/commands/compile/parsers/default.js:98
[DEBUG]         					return childTemplates + '.push(' + state.item.symbol + ');';
[DEBUG]         					                                              ^
[DEBUG] TypeError: Cannot read property 'symbol' of undefined
[DEBUG]     at Object.post (/usr/local/lib/node_modules/alloy/Alloy/commands/compile/parsers/default.js:98:53)
[DEBUG]     at Object.exports.parse (/usr/local/lib/node_modules/alloy/Alloy/commands/compile/parsers/base.js:14:17)
[DEBUG]     at Object.exports.parse (/usr/local/lib/node_modules/alloy/Alloy/commands/compile/parsers/Alloy.Require.js:12:27)
```

**Comment by jamie1192** [comment]
This issue was initially brought up on JIRA over 5 years ago, supposedly "fixed" last year according to this PR and yet is still broken and unresolved, i'm still getting the same crashes as above ^.

**Pull request merged**
