### PR TITLE
[ALOY-1505] Add ability to pass cancel attribute to Option element fo…

### PR DESCRIPTION
**Pull request by feons**
…r OptionDialog

https://jira.appcelerator.org/browse/ALOY-1505

### CODE REVIEW

**Comment by brentonhouse** [comment]
@feons - What would we need to do to get this ready to merge.   Do we just need to get your branch up-to-date?

**Comment by feons** [comment]
@brentonhouse, rebased. Please shower some review love!

**Comment by brentonhouse** [comment]
Awesome!  Thank you @feons!

**Comment by brentonhouse** [comment]
@ewanharris - Is this something we can go ahead and merge?

**Pull request merged**
