### PR TITLE
[ALOY-1262] a directory ending with ".js" causes Alloy compiler error

### PR DESCRIPTION
**Pull request by xavierlacot**
This PR fixes https://jira.appcelerator.org/browse/ALOY-1262
Basically, it checks that items that are going to be optimized are files not directories.
The PR has particularly been checked against test case ALOY-920.

### CODE REVIEW

**Comment by vdesdoigts** [comment]
:+1:

**Comment by feons** [comment]
@xavierlacot, thank you for the PR. 
I'd appreciate it if you'd add a test case, specifically testing for a directory ending with '.js'.

**Comment by xavierlacot** [comment]
Hi @feons, I just added the testcase. You can launch it with:
```
$ jake app:run dir=testing/ALOY-1262
```

**Comment by feons** [comment]
Looks good! **APPROVED.**

**Pull request merged**
