### PR TITLE
[ALOY-1520] Replace Ti.UI.iPhone with Ti.UI.iOS

### PR DESCRIPTION
**Pull request by HazemKhaled**
**JIRA**: https://jira.appcelerator.org/browse/ALOY-1520
Since Titanium SDK 5.4.0 Ti.iPhone namespace show noisy deprecation msg

### CODE REVIEW

**Comment by hansemannn** [comment]
Good catch! @feons the PR basically does the Alloy-part for the migration from {{Ti.UI.iPhone}} proxies to {{Ti.UI.iOS}}. I simply didn't know that Alloy generates specific code there. 

@HazemKhaled Can you do a recursive search for {{Ti.UI.iPhone}} and {{Titanium.UI.iPhone}} to see if there might be other effected Alloy-files as well?

**Comment by nuno** [comment]
We may have check if is:  = or > of 5.4  apply the chance Ti.UI.iOS

**Comment by feons** [comment]
@HazemKhaled, changes look good!
Please also include the check @nuno suggested, also replace `Ti.UI.iPhone` in the generated code. 

Thanks you!

**Comment by nuno** [comment]
@HazemKhaled @feons I took the liberty and created a PR with suggested changes. 

https://github.com/appcelerator/alloy/pull/798

**Comment by feons** [comment]
Close this in favor of https://github.com/appcelerator/alloy/pull/798.
Thank you @HazemKhaled and @nuno!

**Pull request closed without merging**
