### PR TITLE
Add support to set object properties via XML

### PR DESCRIPTION
**Pull request by brentonhouse**
PR for https://jira.appcelerator.org/browse/ALOY-1363

### CODE REVIEW

**Comment by FokkeZB** [comment]
Great work! I guess we need a test app added @feons ?

**Comment by feons** [comment]
Yup! Please include a test app for this PR. Thank you!

**Comment by brentonhouse** [comment]
I haven't done one of the test apps for Alloy before but I will take a look at what it takes to create one.  Thanks!

**Comment by feons** [comment]
@brentonhouse, to get started you can use this command in your Alloy repo `node tools/create_test.js ALOY-###` where `ALOY-###` is the ticket number. That'll create a folder under `test/apps/testing/ALOY-###`, you can fill in code necessary to test the PR.

**Comment by FokkeZB** [comment]
Then use [run](https://github.com/appcelerator/alloy#b-by-cloning-the-repo-and-using-the-jake-test-runner) the test to verify it works and run [generate](https://github.com/appcelerator/alloy/tree/master/tools#create_generated_codejs) and verify the generated code is as it should be. Submit including the generated code and done.

man.. we need to document this better

**Comment by brentonhouse** [comment]
Added test app: https://github.com/brentonhouse/brentonhouse.alloy/tree/feature-xml-attribute-prefix/test/apps/testing/ALOY-1363

**Comment by skypanther** [comment]
@FokkeZB the `create_test.js` file is minimally documented at https://github.com/appcelerator/alloy/tree/master/tools and I think I had added stuff to our internal wiki about it. But, I agree that it should be better documented for contributors.

**Comment by hansemannn** [comment]
@feons @brentonhouse This should go into 2.0.0, can we schedule this?

**Comment by hansemannn** [comment]
@feons Please review. This can even go pre 2.0.0 since I do not see a breaking change here.

**Comment by hansemannn** [comment]
@ewanharris @brentonhouse Ping! Can this please be reviewed? Highly demanded feature.

**Pull request merged**
