### PR TITLE
[ALOY-1493] db_file now accepting function

### PR DESCRIPTION
**Pull request by HazemKhaled**
**JIRA**: https://jira.appcelerator.org/browse/ALOY-1493

example:
```javascript
exports.definition = {
    config: {
        columns: {},
        adapter: {
            type: "sql",
            collection_name: "mytable",
            db_file: function() {
                var myFile = Titanium.Filesystem.getFile(Titanium.Filesystem.applicationDataDirectory, 'file1.sql');
                return myFile.exists() ? myFile.nativePath : Titanium.Filesystem.applicationDataDirectory + 'file2.sql';
            },
            db_name: "projectsDB",
            idAttribute: "UserID",
            remoteBackup: false
        }
    }
};
```

### CODE REVIEW

**Comment by FokkeZB** [comment]
Nice one! Do you have a JIRA ticket with that?

**Comment by HazemKhaled** [comment]
@FokkeZB your reply faster than copying JIRA link :)

**Comment by FokkeZB** [comment]
I'm a 🤖 didn't you know? 😉

**Comment by HazemKhaled** [comment]
shall i create test case?

**Comment by FokkeZB** [comment]
I know my bot forgot something. Before we merge, yes please, but we can also await possible objections to the idea by @feons and others first :)

**Comment by feons** [comment]
@HazemKhaled, yes test case please! thank you!

**Comment by HazemKhaled** [comment]
Test app added

**Comment by feons** [comment]
**APPROVE**

**Pull request merged**
