### PR TITLE
fix(deps): bump xmldom to 0.8.0

### PR DESCRIPTION
**Pull request by karfau**
Switching from package `xmldom` to `@xmldom/xmldom`, which resolves the security issue present in latest xmldom version 0.6.0:
https://github.com/xmldom/xmldom/security/advisories/GHSA-5fg8-2547-mr8q

The reason is that the maintainers were forced to switch to a scoped package since 0.7.0:
 https://github.com/xmldom/xmldom/issues/271

- I used node 12 to run `npm install`.
- I executed `npm run test` on my machine but some tests complained about missing titanium config in my home directory.
  Since I don't know what that means we will have to see what CI checks complain about.

I'm one of the xmldom maintainers. Don't hesitate to ask me questions.

### CODE REVIEW

**Comment by karfau** [comment]
The link in the README to sign the CLA doesn't work for me:
image
Any other way/anything else I should try to sign it?

**Comment by m1ga** [comment]
@karfau thanks for the PR. I'm sure they'll find a way to get this merged :+1:

**Comment by karfau** [comment]
Cool, just to make this clear: I don't care about the attribution, feel free to take the [patch](https://github.com/appcelerator/alloy/pull/1270.patch) and create an own PR from an existing contributor and land it.

All I care about is that less people depend on the outdated verison :smiley:

**Comment by ewanharris** [comment]
@karfau Apologies for that incorrect link, the correct link is https://cla.axway.com/

**Comment by karfau** [comment]
I signed it and all checks are green, happy merging

**Comment by ewanharris** [comment]
Thanks for that @karfau, I'll look to merge this when I return from vacation next week.

**Comment by karfau** [comment]
Happy about it being merged :heart: 

Whats your plan/timeline to publish this to npm?
Will there be a mention here?

**Comment by ewanharris** [comment]
@karfau It should be automatically published within the next 20 minutes or so. We did have automatic PR comments on release but it got spammy so I'll drop a comment when it's released 🙂

**Comment by karfau** [comment]
No need in that case, if it's an automated one I'm fine :)

**Comment by karfau** [comment]
PS: Since all existing xmldom versions have security issues you might want to evaluate if it's reasonable to deprecate version using that dependency.
It depends on, if the XML can be provided/modified by a potential attacker aka if it has to be treated as insecure user input anywhere.

**Pull request merged**
