### PR TITLE
Prevent to optimize widget files which is already optimized.

### PR DESCRIPTION
**Pull request by yomybaby**
When `MVC generation step` of `alloy compile`, widget files are optimized.
So there is no reason to optimize widget file on `OPTIMIZING` step again.

Widget controllers and widget styles are already optimized. It should be listed in exceptions.

Please check below log(alloy 1.94 compile log). `nl.fokkezb.pullToRefresh` widget is optimized twice.
```
[INFO] ----- MVC GENERATION -----
[INFO] [global style] loading from cache...
[INFO] [widgets/kr.yostudio.richeditor/models/richContent.js] model processing...
[INFO] [models/binding.js] model processing...
...
[INFO] [widget.xml] nl.fokkezb.pullToRefresh view processing...
[INFO]   view:       "widget.xml"
[INFO]   controller: "widget.js"
[TRACE] - Processing "builtins" module...
[TRACE] - Processing "optimizer" module...
[TRACE] - Processing "compress" module...
[INFO]   created:    "Resources/iphone/alloy/widgets/nl.fokkezb.pullToRefresh/controllers/widget.js"
[DEBUG]   map:        "build/map/Resources/iphone/alloy/widgets/nl.fokkezb.pullToRefresh/controllers/widget.js.map"
[INFO]   created:     "Resources/iphone/alloy/widgets/nl.fokkezb.pullToRefresh/styles/widget.js"
...
[INFO] ----- OPTIMIZING -----
[INFO] - iphone/alloy/widgets/nl.fokkezb.pullToRefresh/styles/widget.js
[TRACE]   processing "builtins" module...
[TRACE]   processing "optimizer" module...
[TRACE]   processing "compress" module...
```

Optimizing is a quite heavy process. After this PR, you can save compile time.

### CODE REVIEW

**Comment by gimdongwoo** [comment]
Great discovery!!

**Comment by hansemannn** [comment]
@yomybaby Can you file an Alloy-ticket for this? Otherwise it might get lost. Thx!

**Comment by yomybaby** [comment]
I just realized that this PR have failed on jake test.
I'll look into :)

**Comment by hansemannn** [comment]
@yomybaby Where are we with this? Would still love to have it in the next Alloy release.

**Comment by yomybaby** [comment]
I'll look into soon and let you know. 🙏🏻

**Comment by feons** [comment]
@yomybaby, any updates on this? :)

**Comment by yomybaby** [comment]
I found that only js file in `widgets/controllers`are fully optimized when compiling.  (not style file)
Please check again.

**Comment by feons** [comment]
**Approved.** 
https://jira.appcelerator.org/browse/ALOY-1543

**Pull request merged**
