### PR TITLE
Add optimizingExeptions option to config.json

### PR DESCRIPTION
**Pull request by yomybaby**
This PR make you can skip the file when doing an optimization manually.
There are no reason to optimize js files which doesn't depends on alloy.

If you want to skip, add `optimizingExeptions` to `config.json`:
- If `app/lib/q.js`, the path should be `q.js`(see below. After compiling, `app/lib/q.js` to `q.js`)

```javascript
{
  //...
  "optimizingExceptions": [
        "moment2.11.1.js",
        "q.js",
        "underscore1.8.3.js",
        "sf.js",
        "nl.fokkezb.html2as.js"
    ],
  //...
}
```

### CODE REVIEW

**Comment by feons** [comment]
@yomybaby, like the idea! Could you please create a ticket and also fix the conflict. Thanks!

**Comment by yomybaby** [comment]
All done.
https://jira.appcelerator.org/browse/AC-4825

Thanks!

**Comment by feons** [comment]
**Approved.**

**Comment by yomybaby** [comment]
🙏🏻

**Pull request merged**
