### PR TITLE
[ALOY-1520] Replace Ti.UI.iPhone with Ti.UI.iOS with  check if is: = …

### PR DESCRIPTION
**Pull request by nuno**
@HazemKhaled  @feons I took the liberty and created a PR with suggested changes

### CODE REVIEW

**Comment by feons** [comment]
Reviewed and **APPROVED**

**Comment by HazemKhaled** [comment]
Good work, all fine except SystemButton
```
[WARN]  Ti.UI.iPhone.SystemButton.SAVE DEPRECATED in 5.4.0, in favor of Ti.UI.iOS.SystemButton.SAVE
```

```xml
<RightNavButton systemButton="SAVE" platform="ios"/>
```

compiled code
```javascript
$.__views.__alloyId125 = Ti.UI.createButton({
    systemButton: Ti.UI.iOS.SystemButton.SAVE,
    id: "__alloyId125"
});
```

**Comment by nuno** [comment]
compiled code is wrong?

**Comment by HazemKhaled** [comment]
Not wrong,  so where I'm getting the error!! I'll check again

**Comment by feons** [comment]
@HazemKhaled, what's your ti sdk version?

**Comment by nuno** [comment]
@HazemKhaled  I know if you use TiCollectionView module that warn showup.

**Comment by HazemKhaled** [comment]
Ouf, i was sleep maybe, you hero 👍  working fine

**Comment by nuno** [comment]
@HazemKhaled talking to me or to @feons ?  :)

**Comment by HazemKhaled** [comment]
hard question, you all Ti HEROS 💯

**Pull request merged**
