### PR TITLE
[ALOY-1278] Pass model config to migration functions

### PR DESCRIPTION
**Pull request by farwayer**
https://jira.appcelerator.org/browse/TC-5486

It will be nice if sql sync adapter will pass model config to migration functions. It will get access to model columns inside migration for example.

``` javascript
migration.up = function(migrator, config) {
    migrator.createTable(config);
    // other migration actions
};
```

### CODE REVIEW

**Comment by FokkeZB** [comment]
@farwayer could you create a [JIRA ticket](https://jira.appcelerator.org/) for this so it can be discussed and processed?

**Comment by farwayer** [comment]
Already did. Link to jira ticket is in my first message.

**Comment by FokkeZB** [comment]
@farwayer sorry, totally missed that :)

**Comment by feons** [comment]
Move ticket to https://jira.appcelerator.org/browse/ALOY-1278.

@farwayer, thank you for the PR.
Please include a test app necessary to test the changes.

**Comment by brentonhouse** [comment]
:thumbsup:

**Comment by feons** [comment]
**Approved.**

**Pull request merged**
