### PR TITLE
[ALOY-1524] Replace wrench with fs-extra

### PR DESCRIPTION
**Pull request by m1ga**
JIRA-Ticket: https://jira.appcelerator.org/browse/ALOY-1524

Manual testing:
* ti create + alloy new
* alloy generate controller/widget 
* alloy compile

### CODE REVIEW

**Comment by feons** [comment]
@m1ga, thank you for the PR!
Have you signed the CLA [here](http://cla.appcelerator.com)?

**Comment by m1ga** [comment]
yes, CLA is signed

**Comment by feons** [comment]
@m1ga, looks like there are a couple of failed tests, all tests should pass before we can get this merged.

**Comment by m1ga** [comment]
It's strange. The output is something like:

```
  - function __alloyId5() {
  -        $.__views.index.removeEventListener("open", __alloyId5);
  +    function __alloyId7() {
  +        $.__views.index.removeEventListener("open", __alloyId7);
```

so just the alloyId is different and it's shown as an error. I'll check that

**Comment by m1ga** [comment]
Now only 8 tests are failing because of the `matches known good generated code` tests.
Do I need to upload version with this commented back in again?
https://github.com/m1ga/alloy/blob/03a9f02d4c666477354a740c495fb51df995d02a/test/specs/compile.js#L188

**Comment by feons** [comment]
@m1ga, I think what concerns me is that why different codes are generated.

**Comment by m1ga** [comment]
@feons yes, very strange. And it is only on some files where the id is one number higher. All the other `good code` checks are fine

**Comment by feons** [comment]
@m1ga, this probably is a red herring, it happens to `index.xml` in platform folder only. For the test cases, those have index.xml under android folder.

**Comment by m1ga** [comment]
I've just ran the test files with the current Alloy and found out something interesting:

current live alloy version:
```
[PASS] alloy compile testing/ALOY-994b [android] --> compiles without critical error
[PASS] alloy compile testing/ALOY-994b [android] --> leaves no compiler directives in generated code
[PASS] alloy compile testing/ALOY-994b [android] --> has no undefined style entries
[PASS] alloy compile testing/ALOY-994b [ios] --> compiles without critical error
[PASS] alloy compile testing/ALOY-994b [ios] --> leaves no compiler directives in generated code
[PASS] alloy compile testing/ALOY-994b [ios] --> has no undefined style entries
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> compiles without critical error
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> leaves no compiler directives in generated code
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> has no undefined style entries
```


the version from this PR:
```
[PASS] alloy compile testing/ALOY-994b [android] --> compiles without critical error
[PASS] alloy compile testing/ALOY-994b [android] --> leaves no compiler directives in generated code
[PASS] alloy compile testing/ALOY-994b [android] --> has no undefined style entries
[PASS] alloy compile testing/ALOY-994b [android] --> generated a alloy/controllers/index.js file
[FAIL] alloy compile testing/ALOY-994b [android] --> matches known good generated code for alloy/controllers/index.js
[PASS] alloy compile testing/ALOY-994b [android] --> generated a alloy/controllers/win2.js file
[FAIL] alloy compile testing/ALOY-994b [android] --> matches known good generated code for alloy/controllers/win2.js
[PASS] alloy compile testing/ALOY-994b [ios] --> compiles without critical error
[PASS] alloy compile testing/ALOY-994b [ios] --> leaves no compiler directives in generated code
[PASS] alloy compile testing/ALOY-994b [ios] --> has no undefined style entries
[PASS] alloy compile testing/ALOY-994b [ios] --> generated a alloy/controllers/index.js file
[PASS] alloy compile testing/ALOY-994b [ios] --> matches known good generated code for alloy/controllers/index.js
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> compiles without critical error
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> leaves no compiler directives in generated code
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> has no undefined style entries
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> generated a alloy/controllers/index.js file
[PASS] alloy compile testing/ALOY-994b [mobileweb] --> matches known good generated code for alloy/controllers/index.js
```

So the current version doesn't even test the good code check that fails in my PR ? Might this be the problem :)

**Comment by m1ga** [comment]
I'll start again in smaller steps to see where the problem is. So I'll close this one and create a new PR

**Pull request closed without merging**
