### PR TITLE
v1.11.0

### PR DESCRIPTION
**Pull request by ewanharris**
Bump to 1.11.0

### CODE REVIEW

**Comment by hansemannn** [comment]
Can we move the features out of 1.10.12, so devs do not think it's an irrelevant update.

**Comment by ewanharris** [comment]
@hansemannn I don't think we should, 1.10.12 has shipped with those tickets. This just brings the version number in line with the changes we made, so that when we release 7.0.2 CLI (or should it be 7.1.0 with these alloy changes?) the alloy version bump indicates some new features

**Comment by hansemannn** [comment]
In a perfect semantic versioning world, it should be 7.1.0 I guess. @ingo thoughts?

**Comment by ewanharris** [comment]
Oh no, @build has become sentient! :)

**Pull request merged**
