### PR TITLE
[ALOY-1321] iOS: remove unsupported app icons and launch images for new projects

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/ALOY-1321

### CODE REVIEW

**Comment by FokkeZB** [comment]
I see you're also removing launch image? The ticket is just about icons and we don't generate launch images so I think they are still needed?

**Comment by feons** [comment]
I removed the unsupported ones. Are they needed?

**Comment by FokkeZB** [comment]
Well, the ticket is only about the icons, since with `DefaultIcon.png` we no longer need these here. But the launch images are still required, at least until we equip our templates with the new storyboard launch files we'll introduce with 5.2 if I'm correct.

**Comment by feons** [comment]
It's a good thinking on the single responsibility principle!

**Comment by FokkeZB** [comment]
Looks good now, but you can remove the 2 iTunesArtwork files as well from:
https://github.com/feons/alloy/tree/ALOY-1321/platforms/ios/project/app/assets/iphone

These are generated (for adhoc only) as well:
https://github.com/appcelerator/titanium_mobile/blob/816d68323c588bd1143c2f9bb8f52dbd65e08255/iphone/cli/commands/_build.js#L4509-L4510

**Comment by feons** [comment]
**Approved.**

**Pull request merged**
